"""End-to-end data preparation pipeline for one or all OS types.

Steps:
  1. Parse raw logs with Drain → structured CSV + templates CSV
  2. Build sentence embeddings (BERT + TF-IDF)
  3. Build component map
  4. Split into train/test CSVs

Usage:
    python scripts/prepare_all.py --os linux
    python scripts/prepare_all.py --os linux windows mac network
    python scripts/prepare_all.py  # all OS types
"""
import argparse
import sys
from pathlib import Path

# Allow importing src.*
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from omegaconf import OmegaConf

from src.data.parsers import get_parser
from src.data.embedder import build_embeddings
from src.data.labeler import build_component_map, split_and_save


CONF_DIR = Path(__file__).resolve().parent.parent / "conf" / "data"


def prepare_os(os_type: str, bert_model_path: str, device: str = "cpu"):
    cfg_path = CONF_DIR / f"{os_type}.yaml"
    if not cfg_path.exists():
        print(f"[{os_type}] Config not found: {cfg_path}")
        return

    cfg = OmegaConf.load(str(cfg_path))
    print(f"\n{'='*50}\n[{os_type.upper()}] Starting data preparation\n{'='*50}")

    # ── Step 1: Parse logs ─────────────────────────────────────────────────
    print("\n[1/4] Parsing raw logs...")
    parser = get_parser(os_type, cfg)
    df = parser.parse()
    print(f"  Parsed {len(df):,} log entries. Label distribution:\n  {df['Label'].value_counts().to_dict()}")

    # ── Step 2: Sentence embeddings ────────────────────────────────────────
    print("\n[2/4] Building sentence embeddings...")
    seq_dir = Path(cfg.sequences_dir)
    seq_dir.mkdir(parents=True, exist_ok=True)

    drain_out = Path(cfg.raw_dir) / "drain_out"
    # Find templates CSV generated by Drain (any source file)
    template_files = list(drain_out.glob("*_templates.csv"))
    if not template_files:
        # Fallback: build one from df
        import pandas as pd
        import hashlib
        templates_df = df[["EventId", "Content"]].drop_duplicates("EventId").copy()
        templates_df = templates_df.rename(columns={"Content": "EventTemplate"})
        templates_df["Occurrences"] = templates_df["EventId"].map(df["EventId"].value_counts())
        templates_csv_path = seq_dir / f"{os_type}_templates.csv"
        templates_df.to_csv(templates_csv_path, index=False)
        template_src = str(templates_csv_path)
    else:
        # Merge and deduplicate templates across all source files
        import pandas as pd
        merged = pd.concat([pd.read_csv(f) for f in template_files]).drop_duplicates("EventId")
        template_src = str(seq_dir / f"{os_type}_templates.csv")
        merged.to_csv(template_src, index=False)

    emb_json = str(seq_dir / f"{os_type}_sentences_emb.json")
    build_embeddings(template_src, bert_model_path, emb_json, device_str=device)

    # ── Step 3: Component map ──────────────────────────────────────────────
    print("\n[3/4] Building component map...")
    com_json = str(seq_dir / f"{os_type}_component.json")
    build_component_map(df, com_json)

    # ── Step 4: Split sequences ────────────────────────────────────────────
    print("\n[4/4] Splitting train/test sequences...")
    split_and_save(df, str(seq_dir), window_size=cfg.window_size)

    print(f"\n[{os_type.upper()}] Done. Artifacts in {seq_dir}")


def main():
    parser = argparse.ArgumentParser(description="Prepare all data for CSCLog training")
    parser.add_argument(
        "--os",
        nargs="+",
        default=["linux", "windows", "mac", "network"],
        choices=["linux", "windows", "mac", "network"],
    )
    parser.add_argument(
        "--bert",
        default=str(Path(__file__).resolve().parent.parent.parent / "CSCLog" / "model" / "bert"),
        help="Path to BERT model directory",
    )
    parser.add_argument("--device", default="cpu", choices=["cpu", "cuda"])
    args = parser.parse_args()

    args.bert = str(Path(args.bert).resolve())

    for os_type in args.os:
        try:
            prepare_os(os_type, args.bert, args.device)
        except Exception as e:
            print(f"[{os_type}] ERROR: {e}")
            import traceback; traceback.print_exc()


if __name__ == "__main__":
    main()
